In [113]:
import pandas as pd

df = pd.read_csv('clubs.csv')
df

,club_id,club_code,name,domestic_competition_id,total_market_value,squad_size,average_age,foreigners_number,foreigners_percentage,national_team_players,stadium_name,stadium_seats,net_transfer_record,coach_name,last_season,filename,url
0,105,sv-darmstadt-98,Sportverein Darmstadt 1898 e. V.,L1,NaN,30,26.3,11,36.7,1,Merck-Stadion am Böllenfalltor,17810,€-1.48m,NaN,2023,../data/raw/transfermarkt-scraper/2023/clubs.j...,https://www.transfermarkt.co.uk/sv-darmstadt-9...
1,11127,ural-ekaterinburg,FK Ural Yekaterinburg,RU1,NaN,27,27.5,15,55.6,7,Yekaterinburg Arena,23000,€-770k,NaN,2023,../data/raw/transfermarkt-scraper/2023/clubs.j...,https://www.transfermarkt.co.uk/ural-ekaterinb...
2,114,besiktas-istanbul,Beşiktaş Jimnastik Kulübü,TR1,NaN,30,27.3,14,46.7,12,Tüpraş Stadyumu,42590,€-14.50m,NaN,2023,../data/raw/transfermarkt-scraper/2023/clubs.j...,https://www.transfermarkt.co.uk/besiktas-istan...
3,12,as-rom,Associazione Sportiva Roma,IT1,NaN,27,26.6,18,66.7,17,Olimpico di Roma,73261,+€72.25m,NaN,2023,../data/raw/transfermarkt-scraper/2023/clubs.j...,https://www.transfermarkt.co.uk/as-rom/startse...
4,148,tottenham-hotspur,Tottenham Hotspur Football Club,GB1,NaN,28,25.5,22,78.6,21,Tottenham Hotspur Stadium,62850,€-154.90m,NaN,2023,../data/raw/transfermarkt-scraper/2023/clubs.j...,https://www.transfermarkt.co.uk/tottenham-hots...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
421,68608,cf-os-belenenses,CF Os Belenenses,PO1,NaN,30,25.7,5,16.7,0,Estádio do Restelo,19980,+-0,NaN,2017,../data/raw/transfermarkt-scraper/2017/clubs.j...,https://www.transfermarkt.co.uk/cf-os-belenens...
422,724,fc-volendam,Football Club Volendam,NL1,NaN,30,22.2,17,56.7,4,Kras Stadion,7384,+€1.80m,NaN,2023,../data/raw/transfermarkt-scraper/2023/clubs.j...,https://www.transfermarkt.co.uk/fc-volendam/st...
423,800,atalanta-bergamo,Atalanta Bergamasca Calcio S.p.a.,IT1,NaN,25,26.8,18,72.0,16,Gewiss Stadium,21747,+€72.82m,NaN,2023,../data/raw/transfermarkt-scraper/2023/clubs.j...,https://www.transfermarkt.co.uk/atalanta-berga...
424,979,moreirense-fc,Moreirense Futebol Clube,PO1,NaN,27,25.9,15,55.6,2,Estádio C. J. de Almeida Freitas,6153,€-2.05m,NaN,2023,../data/raw/transfermarkt-scraper/2023/clubs.j...,https://www.transfermarkt.co.uk/moreirense-fc/...
425,984,west-bromwich-albion,West Bromwich Albion,GB1,NaN,25,27.8,8,32.0,4,The Hawthorns,26850,€-1.35m,NaN,2020,../data/raw/transfermarkt-scraper/2020/clubs.j...,https://www.transfermarkt.co.uk/west-bromwich-...

In [114]:
#check the data type of the dataset
df.dtypes

club_id                      int64
club_code                   object
name                        object
domestic_competition_id     object
total_market_value         float64
squad_size                   int64
average_age                float64
foreigners_number            int64
foreigners_percentage      float64
national_team_players        int64
stadium_name                object
stadium_seats                int64
net_transfer_record         object
coach_name                 float64
last_season                  int64
filename                    object
url                         object
dtype: object

In [124]:
#checking duplicates

df.duplicated().sum()

0

In [115]:
#finding null values in the dataset

df.isnull().sum()

club_id                      0
club_code                    0
name                         0
domestic_competition_id      0
total_market_value         426
squad_size                   0
average_age                 38
foreigners_number            0
foreigners_percentage       47
national_team_players        0
stadium_name                 0
stadium_seats                0
net_transfer_record          0
coach_name                 426
last_season                  0
filename                     0
url                          0
dtype: int64

In [116]:
from unidecode import unidecode

df['name'] = df['name'].apply(unidecode)

In [117]:
#dropping the unnecessary columns
'''
1 - club_code
2 - name
3 - squad_size
4 - foreign_numbers
5 - foreign_percentage
6 - national_team_players
7 - coach_name
8 - last_season
9 - filename
10 - url
11 - total_market_value
'''

df = df.drop(['club_code','name', 'squad_size', 'foreigners_number', 'foreigners_percentage','national_team_players', 'coach_name', 'last_season', 'filename', 'url', 'total_market_value'], axis=1)

In [118]:
#converting unicode to correct data

df['stadium_name'] = df['stadium_name'].apply(unidecode)

In [119]:
#cleaning 'net_transfer_record'

#renaming 'net_transfer_record' to 'net_transfer_record_in_euros'
df.rename(columns={'net_transfer_record': 'net_transfer_record_in_euros'}, inplace=True)

#removing '€' by replacing it with an empty string

df['net_transfer_record_in_euros'] = df['net_transfer_record_in_euros'].str.replace('€', '')

#cheching the data type

df['net_transfer_record_in_euros'].dtype

#converting the data type
'''

Need to need to convert the data type

'''

'\nNeed to need to convert the data type to float\n'

In [120]:
#replacing null values for 'average_age' with the random impution
import random

random_age = random.choice(df['average_age'])
random_age

df['average_age'].fillna(random_age, inplace=True)

In [121]:
df.to_csv('clubs_cleaned.csv', index=False)

In [122]:
df['average_age'].max()

28.8

In [123]:
df

,club_id,domestic_competition_id,average_age,stadium_name,stadium_seats,net_transfer_record_in_euros
0,105,L1,26.3,Merck-Stadion am Bollenfalltor,17810,-1.48m
1,11127,RU1,27.5,Yekaterinburg Arena,23000,-770k
2,114,TR1,27.3,Tupras Stadyumu,42590,-14.50m
3,12,IT1,26.6,Olimpico di Roma,73261,+72.25m
4,148,GB1,25.5,Tottenham Hotspur Stadium,62850,-154.90m
...,...,...,...,...,...,...
421,68608,PO1,25.7,Estadio do Restelo,19980,+-0
422,724,NL1,22.2,Kras Stadion,7384,+1.80m
423,800,IT1,26.8,Gewiss Stadium,21747,+72.82m
424,979,PO1,25.9,Estadio C. J. de Almeida Freitas,6153,-2.05m
425,984,GB1,27.8,The Hawthorns,26850,-1.35m